baseURL = "http://example.org/"
languageCode = "en-us"
title = "Town Hall"
theme = "town_hall_theme"
themesDir = "./themes"


[[menu.main]]
    name =  "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "municipal council"
    url = "/municipalCouncil"
    weight = 2
[[menu.main]]
    name = "associations"
    url = "/associations"
    weight = 3

    # https://discourse.gohugo.io/t/how-to-create-multilevel-dropdown-menu-in-hugo/18373/4

# EVENTS AND SUBCATEGORIE FOR EVENTS 
[[ menu.main ]]
    identifier = "events"
    name = "events"
    url = "/events"
    weight = 4 

[[ menu.main]]
    parent = "events" 
    name = "All events"
    url = "/events"
    weight = 1

[[ menu.main]]
    parent = "events" 
    name = "Upcoming events"
    url = "/events"
    weight = 2

[[ menu.main]]
    parent = "events"
    name = "Archived events"
    url = "/something"
    weight = 3

[[ menu.main]]
    parent = "events" 
    name = "Calendar"
    url = "/events"
    weight = 4



[params]
    homeText = "Some text for test"
    homeText2 = "Some more text"




